export const themes = {
    "Active4D": "Active4D",
    "AllHallowsEve": "All Hallows Eve",
    "Amy": "Amy",
    "BirdsofParadise": "Birds of Paradise",
    "Blackboard": "Blackboard",
    "BrillianceBlack": "Brilliance Black",
    "BrillianceDull": "Brilliance Dull",
    "ChromeDevTools": "Chrome DevTools",
    "CloudsMidnight": "Clouds Midnight",
    "Clouds": "Clouds",
    "Cobalt": "Cobalt",
    "Cobalt2": "Cobalt2",
    "Dawn": "Dawn",
    "DominionDay": "Dominion Day",
    "Dracula": "Dracula",
    "Dreamweaver": "Dreamweaver",
    "Eiffel": "Eiffel",
    "EspressoLibre": "Espresso Libre",
    "GitHubDark": "GitHub Dark",
    "GitHubLight": "GitHub Light",
    "GitHub": "GitHub",
    "IDLE": "IDLE",
    "idleFingers": "idleFingers",
    "iPlastic": "iPlastic",
    "Katzenmilch": "Katzenmilch",
    "krTheme": "krTheme",
    "Kuroir Theme": "Kuroir Theme",
    "LAZY": "LAZY",
    "MagicWB (Amiga)": "MagicWB (Amiga)",
    "MerbivoreSoft": "Merbivore Soft",
    "Merbivore": "Merbivore",
    "monoindustrial": "monoindustrial",
    "MonokaiBright": "Monokai Bright",
    "Monokai": "Monokai",
    "NightOwl": "Night Owl",
    "Nord": "Nord",
    "OceanicNext": "Oceanic Next",
    "PastelsonDark": "Pastels on Dark",
    "SlushandPoppies": "Slush and Poppies",
    "Solarized-dark": "Solarized-dark",
    "Solarized-light": "Solarized-light",
    "SpaceCadet": "SpaceCadet",
    "Sunburst": "Sunburst",
    "Textmate(MacClassic)": "Textmate (Mac Classic)",
    "themelist": "themelist",
    "Tomorrow-Night-Blue": "Tomorrow-Night-Blue",
    "Tomorrow-Night-Bright": "Tomorrow-Night-Bright",
    "Tomorrow-Night-Eighties": "Tomorrow-Night-Eighties",
    "Tomorrow-Night": "Tomorrow-Night",
    "Tomorrow": "Tomorrow",
    "Twilight": "Twilight",
    "UpstreamSunburst": "Upstream Sunburst",
    "VibrantInk": "Vibrant Ink",
    "Xcode_default": "Xcode_default",
    "Zenburnesque": "Zenburnesque"
}
